### PR TITLE
Add ParOpt to pyOptSparse

### PR DESCRIPTION
**Pull request by gjkennedy**
## Purpose
This pull request wraps ParOpt within pyoptsparse. The wrapper is a straightforward extension of existing pyoptsparse wrappers. Some capabilities of ParOpt are not included such as parallel design vectors.

## Type of change
- New feature (non-breaking change which adds functionality)

## Testing
I tested the ParOpt wrapper with the python examples in the pyoptsparse/examples directory.

## Checklist

- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by johnjasa** [comment]
Graeme, thanks for this PR! Could you please point me towards the tests and docs for ParOpt? I couldn't find them right off.

**Comment by gjkennedy** [comment]
Hey John,

Do you mean the general docs for ParOpt? Or pyoptsparse-specific paropt docs?

General docs are located here: https://gjkennedy.github.io/paropt/

I just ran tests in examples with the argument --opt paropt


--
Graeme J. Kennedy, PhD
Assistant Professor
School of Aerospace Engineering
Georgia Institute of Technology
270 Ferst Dr, Atlanta, GA 30332-0150
http://gkennedy.gatech.edu<http://gkennedy.gatech.edu/>


________________________________

**Comment by johnjasa** [comment]
Sorry for the confusion.

For the docs, I mean a small write-up explaining what ParOpt is and how to use it, but within the PyOptSparse docs. It could just be a sentence and a link to the ParOpt docs. Here's an example for SNOPT: http://mdolab.engin.umich.edu/docs/packages/pyoptsparse/doc/optimizers/pysnopt.html and here's where those docs live in the repo: https://github.com/mdolab/pyoptsparse/tree/master/doc/optimizers  Could you please type up a bit about what you want to say or link to for ParOpt and add that to the PR?

For the tests, it'd be including tests that get run with the automated testing tool. So wherever we have tests for certain types of optimizers already, add in a method to test ParOpt. Here's an example: https://github.com/mdolab/pyoptsparse/blob/master/test/test_hs015.py#L100 I can go through an do that for all the tests once I get ParOpt going locally.

**Comment by johnjasa** [comment]
I added a test for ParOpt to `test_hs015.py`, but it doesn't get the same answer as other optimizers. Perhaps I have installed ParOpt incorrectly or need to change some settings? I've pushed up my branch with the test here: https://github.com/johnjasa/pyoptsparse/tree/testing_paropt and then here's the actual test: https://github.com/johnjasa/pyoptsparse/blob/testing_paropt/test/test_hs015.py

Here's the output I get:
```======================================================================
FAIL: test_paropt (__main__.TestHS15)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_hs015.py", line 104, in test_paropt
    self.optimize('paropt')
  File "test_hs015.py", line 83, in optimize
    self.assertAlmostEqual(sol.objectives['obj'].value, 306.5, places=5)
AssertionError: 360.37976720759747 != 306.5 within 5 places
```

Does this test work locally for you?

**Comment by gjkennedy** [comment]
Hi John,

There's a problem with this test.

The problem is non-convex - please see attached image. The paropt solution is the lower left, the asserted solution is the upper right.

Graeme

--
Graeme J. Kennedy, PhD
Assistant Professor
School of Aerospace Engineering
Georgia Institute of Technology
270 Ferst Dr, Atlanta, GA 30332-0150
http://gkennedy.gatech.edu<http://gkennedy.gatech.edu/>


________________________________

**Comment by JustinSGray** [comment]
@gjkennedy, attachment didn't come through...

**Comment by gjkennedy** [comment]
So I missed these tests, here are a few issues:

  1.  Interior point methods don't like starting from the bounds. I'm not sure how IPOPT is handling it, but ParOpt perturbs the design point so that it is away from the bounds (in the interior). pyoptsparse is copying it's own design vector values, and re-setting the those into the optimizer, producing NaNs everywhere for some optimization problems that start from the minimizer.
  2.  Large bounds, e.g. 1e19, are not the same as no bounds for interior point methods. These produce barrier functions that are unbounded from below. This causes lots of issues for scaling etc. I'd argue, that's not really a fair test.

These issues can be "solved" by adding pre- or post- processing layers, but then, I would argue, what's the purpose of pyOptSparse?

I can add the optimizer description to the documentation.

A few other things that I'll have to work on with ParOpt:

  1.  Adding a mixture of equality and inequality constraints.
  2.  Dealing with variables with identical upper/lower bounds

--
Graeme J. Kennedy, PhD
Assistant Professor
School of Aerospace Engineering
Georgia Institute of Technology
270 Ferst Dr, Atlanta, GA 30332-0150
http://gkennedy.gatech.edu<http://gkennedy.gatech.edu/>


________________________________

**Comment by gjkennedy** [comment]
Figure_2

Please see above for the image.

**Comment by gjkennedy** [comment]
`        # Check Solution
        fobj = sol.objectives['obj'].value
        diff = np.min(np.abs([fobj - 306.5, fobj - 360.379767]))
        self.assertAlmostEqual(diff, 0.0, places=5)

        xstar1 = (0.5, 2.0)
        xstar2 = (-0.79212322, -1.26242985)
        x1 = sol.variables['xvars'][0].value
        x2 = sol.variables['xvars'][1].value

        diff = np.min(np.abs([xstar1[0] - x1, xstar2[0] - x1]))
        self.assertAlmostEqual(diff, 0.0, places=5)

        diff = np.min(np.abs([xstar1[1] - x2, xstar2[1] - x2]))
        self.assertAlmostEqual(diff, 0.0, places=5)

**Comment by johnjasa** [comment]
Thanks for the further info. I understand that PyOptSparse is setting things up to mess with interior point methods (like taking `None` bounds to be `1e20`).

I'll bring up some of these issues with other MDO Lab folk this week and talk through how we want to handle them. Thanks for the snippet for the test to work with both minima!

**Comment by gjkennedy** [comment]
I added links in the documentation, and pushed suggested changes to the regression tests.

**Comment by JustinSGray** [comment]
@gjkennedy you raised some good points that I was unaware of with regard to IP methods. 

I suggest, if you haven't already done this (i admit I haven't read the docs in your PR yet) that you add a few notes to the same effect in the docs of parOpt or pyoptsparse itself.

**Comment by nwu63** [comment]
I just took a look and some changes related to scaling the Lagrange multipliers in pySNOPT are throwing errors when linear constraints are present. The `optProb.offset` dimension doesn't match the dimension of the Lagrange multiplier, and I couldn't really figure out what was going on. I suggest that we remove the scaling code in pySNOPT for now, unless someone is willing to look into this more.

To reproduce the error, run `test_tp109.py`. The line that threw the error is line 1253 in `deprocessconstraints` in `pyOpt_optimization.py`:
`fcon_in += self.offset`

As for getting different answers, do we need special handling of unbounded DVs in pyOptSparse? Perhaps we want separate test cases for interior point methods that always have bounds?

**Comment by JustinSGray** [comment]
@nwu63 just FYI, you could have also just submitted your own PR from your fork. It would have kept all @gjkennedy's commit history in tact. I think it may have also even closed his open PR when you accepted yours ... 

github is pretty smart about all that

**Comment by johnjasa** [comment]
Cool, I didn't realize that, I suggested Neil do it this way to make sure @gjkennedy gets all the credit. I understand by doing it your suggested way all the commits stay in tact. Thanks!

**Comment by nwu63** [comment]
Apologies I really messed this up, I was going to just add the commit to graeme's fork and then close the PR but I pushed the wrong branch. I'll just make a new PR and merge that in, sorry about that...

**Pull request closed without merging**
