### PR TITLE
Removed patch version from dependencies

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
This is a re-submission of #159 but without any modifications to `requirements.txt`. I simply removed the patch versions from dependencies.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- Maintenance

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
Note that the RTD build actually passed after I changed the settings back. For some reason the status is not updated, and I don't want to commit again just to trigger a fresh build.

**Review by marcomangano — APPROVED** [review]

**Comment by sseraj** [comment]
Where did you see that the RTD build passed?

**Comment by nwu63** [comment]
I can't find it anymore, maybe it got overwritten or something. I don't know how to trigger a new build without another commit which I am hesitant to do.

**Comment by eirikurj** [comment]
The Latest build in this series is [this one](https://readthedocs.com/projects/mdolab-pyoptsparse/builds/417983/) which does indeed pass.

**Review by sseraj — APPROVED** [review]

**Pull request merged**
