### PR TITLE
Remove deprecations

### LINKED ISSUE #359: NumPy 2.0 compatibility
This is more or less a heads-up about the upcoming NumPy 2.0 release: https://github.com/numpy/numpy/issues/24300

A quick look test shows at least one incompatibility:

```
  File "/mdao/u/swryan/.conda/envs/openmdao_20231016-120012/lib/python3.11/site-packages/pyoptsparse/__init__.py", line 3, in <module>
    from .pyOpt_history import History
  File "/mdao/u/swryan/.conda/envs/openmdao_20231016-120012/lib/python3.11/site-packages/pyoptsparse/pyOpt_history.py", line 12, in <module>
    from .pyOpt_utils import EPS
  File "/mdao/u/swryan/.conda/envs/openmdao_20231016-120012/lib/python3.11/site-packages/pyoptsparse/pyOpt_utils.py", line 23, in <module>
    from .types import ArrayType
  File "/mdao/u/swryan/.conda/envs/openmdao_20231016-120012/lib/python3.11/site-packages/pyoptsparse/types.py", line 9, in <module>
    NumpyType = Union[float, npt.NDArray[np.float_]]
                                         ^^^^^^^^^
  File "/mdao/u/swryan/.conda/envs/openmdao_20231016-120012/lib/python3.11/site-packages/numpy/__init__.py", line 388, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
```

### LINKED ISSUE #361: NumPy 1.25 deprecation
## Description

Multiple occurrences of the following deprecation:

```
Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
```

https://numpy.org/doc/stable/release/1.25.0-notes.html#deprecations

### Steps to reproduce issue

```
~/dev/pyoptsparse/tests$ testflo --show_deprecations test_hs015.py:TestHS15
S.....S..
Deprecations Report
===================

1 unique deprecation warnings were captured:

--
Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)

    /tmp/tmpcmadqpo6/pyoptsparse/pySNOPT/pySNOPT.py, line 719
    [test_hs015.py:TestHS15.test_snopt]

    /tmp/tmpcmadqpo6/pyoptsparse/pySNOPT/pySNOPT.py, line 491
    [test_hs015.py:TestHS15.test_snopt_snstop]

    /tmp/tmpcmadqpo6/pyoptsparse/pySNOPT/pySNOPT.py, line 717
    [test_hs015.py:TestHS15.test_snopt_snstop]

    /tmp/tmpcmadqpo6/pyoptsparse/pySLSQP/pySLSQP.py, line 218
    [test_hs015.py:TestHS15.test_optimization_0_SLSQP]

    /tmp/tmpcmadqpo6/pyoptsparse/pySNOPT/pySNOPT.py, line 725
    [test_hs015.py:TestHS15.test_snopt]

    /tmp/tmpcmadqpo6/pyoptsparse/pySNOPT/pySNOPT.py, line 715
    [test_hs015.py:TestHS15.test_snopt]

    /tmp/tmpcmadqpo6/pyoptsparse/pySNOPT/pySNOPT.py, line 491
    [test_hs015.py:TestHS15.test_snopt]

    ... etc.
```

### Current behavior

deprecation warnings

### Expected behavior

no deprecation warnings

### Code versions

- Operating System: Ubuntu 20.04
- Python: 3.11
- Numpy 1.25
- This repository: v2.10.1

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose

Closes #361,
Closes #359.

Also updated the `testflo` flag since we now have IPOPT on Intel images.

## Expected time until merged

1 week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
I'm a little confused, maybe I'm too out of it now
* Why did coverage go down when I submitted the PR from a branch?
* Why did the `--disallow_skipped` flag not return exit 2 when we had one skipped test?

**Comment by swryan** [comment]
> * Why did the `--disallow_skipped` flag not return exit 2 when we had one skipped test?
>   
>   * Update: I've opened [Fix bug with `disallow_skipped` option OpenMDAO/testflo#96](https://github.com/OpenMDAO/testflo/pull/96) to address this

This PR has been merged and a new [release ](https://github.com/OpenMDAO/testflo/blob/master/RELEASE_NOTES.md)of `testflo` (1.4.14) has been pushed to [pypi ](https://pypi.org/project/testflo/)with the bug fix.

**Comment by nwu63** [comment]
Think we may have to wait the full cycle for base/deps to rebuild.. why did we put some testing requirements in that layer anyways? Shouldn't they get picked up when we install `pip install .[testing]`? @eirikurj

**Comment by nwu63** [comment]
This PR is ready @marcomangano @ArshSaja

**Comment by eirikurj** [comment]
@nwu63 yeah, we need to wait for the deps images to be updated for an updated `testflo`. Ironically, we could use the feature in of https://github.com/mdolab/docker/pull/252 now, but tests are failing because it needs this PR. 

>why did we put some testing requirements in that layer anyways?

Primarily, since they are intended for testing we chose to install packages that are common to all downstream layers upfront. Aside from that I think at the time many package had an "incomplete" `setup.py` file, e.g., did not have `testing` entry or were missing packages.  I think if we do not want to fix the `testflo` version in our docker images (enforced with the constraint file), then a floting version (installed as part of setup the first time it appears) is probaby fine. However, we need to do this in steps as I think many packages are still missing the `pip install .[testing]` in our build scripts.

**Comment by nwu63** [comment]
I think explicitly listing the testing requirements is good regardless. I don't believe we are fixing the testflo version in the constraint file, but that is fine as long as the requirements are consistent across packages. In the _most_ ideal case, we would be testing each package separately even in the nightly Docker cronjobs, so one package does not affect another downstream. Maybe that's discussion for another time.

Please approve/merge this soon as the nightly builds will start failing.

**Review by eirikurj — APPROVED** [review]
Changes look good. Deprecation warnings are gone (tested with same case locally as https://github.com/mdolab/pyoptsparse/issues/359). Did not explicitly test numpy 2.0 changes, but these are straight forward.

**Comment by eirikurj** [comment]
@marcomangano @ArshSaja please review

**Review by marcomangano — APPROVED** [review]
I don't have the bandwidth to test this right now, but LGTM

**Review by ArshSaja — APPROVED** [review]

**Pull request merged**
