### PR TITLE
Update informs list to be consistent with SNOPT 7.7 + updating docstrings for flake8 rst checks

### LINKED ISSUE #332: Missing pySNOPT information code for timeout
## Description

When running SNOPT through `pySNOPT`, using the `Time limit` SNOPT option, `pyoptsparse`/`pySNOPT` fails with a key error if the time limit is reached, because [the code for timeout is not handled in `pySNOPT`](https://github.com/mdolab/pyoptsparse/blob/main/pyoptsparse/pySNOPT/pySNOPT.py#L137).

### Steps to reproduce issue

Run any SNOPT optimization with arg `options= {"Time limit": 20}`.

### Current behavior

`KeyError: 34`

### Expected behavior

Return result, showing [informational code #34 from p. 42 of the SNOPT manual](http://www.sbsi-sol-optimize.com/manuals/SNOPT%20Manual.pdf).

### Suggested fix:

Insert
```
            34: "time limit reached",
```
at [pySNOPT.py, line 137](https://github.com/mdolab/pyoptsparse/blob/main/pyoptsparse/pySNOPT/pySNOPT.py#L137)

### PR DESCRIPTION
**Pull request by marcomangano**
## Purpose

I updated the `informs` dictionary to include all the supported `INFO` exit codes in SNOPT 7.7 (see list on the [manual](http://www.sbsi-sol-optimize.com/manuals/SNOPT%20Manual.pdf), page 42).
A few of the current codes are not used in v7.7 anymore, so I removed them from the list. This will not affect backward compatibility as we don't support versions <7.7.

Closes #332 

P.S. I edited a few docstrings that were creating issues with the new flake8 rst checks, since this is the first PR affected by the new check for this repo

## Expected time until merged

1-2 days

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Review by sseraj — COMMENTED** [review]
It seems like we have only supported 7.7.x for a while now (since v2.0). Maybe we can just remove the old informs?

**Comment by marcomangano** [comment]
> It seems like we have only supported 7.7.x for a while now (since v2.0). Maybe we can just remove the old informs?

Oh right, I was being overly conservative. Removing now

**Comment by nwu63** [comment]
Have you tried the time limit option in SNOPT? I don't think we should recommend things until we've tried it and feel comfortable with replacing it.

**Comment by marcomangano** [comment]
> Have you tried the time limit option in SNOPT? I don't think we should recommend things until we've tried it and feel comfortable with replacing it.

I tested it and it works as intended, but I will a test for this in the next few days

**Review by sseraj — APPROVED** [review]

**Review by lamkina — APPROVED** [review]

**Pull request merged**
