### PR TITLE
Changing the SLSQP output file id

### PR DESCRIPTION
**Pull request by eirikurj**
## Purpose
Closes https://github.com/mdolab/MACH-Aero/issues/31. 
File id 6 is often associated with `stdout` and as such was redirecting the adflow output to this file.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Run the tutorial as described in https://github.com/mdolab/MACH-Aero/issues/31.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by marcomangano — APPROVED** [review]
Nice, finally! Can't test it rn but as long as you can get ADflow iters on the terminal I am happy with this.

**Review by nwu63 — APPROVED** [review]
Can confirm this worked as expected with MACH-Aero. Is the unit number 6 something that was hard-coded in ADflow? If it's general for `stdout` why did it not redirect Python outputs?

**Comment by eirikurj** [comment]
No not hardcoded. In Fortran assigning 6 to stdout is not a standard but more like a convention (and a very widely used one). This can be changed in code or on a compiler level. Here * directs to 6 (the default for gfortran), i.e. when adflow calls `write(*,*)` it is the same as calling `write(6,*)`. Python follows the C convention and uses 1.

**Comment by nwu63** [comment]
> No not hardcoded. In Fortran assigning 6 to stdout is not a standard but more like a convention (and a very widely used one). This can be changed in code or on a compiler level. Here * directs to 6 (the default for gfortran), i.e. when adflow calls `write(*,*)` it is the same as calling `write(6,*)`. Python follows the C convention and uses 1.

I see, so Fortran happens to use 6 and there was a clash between SLSQP and ADflow? I guess for SNOPT we use different unit numbers for print and summary files so I guess that's why it's not an issue there. THanks.

**Pull request merged**
