### PR TITLE
Update meson version for windows

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose

Now that mesonbuild/meson#10778 is fixed in release 1.3.1, I bumped the meson version in the `environment.yml` file.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by marcomangano** [comment]
It looks like there are still issues with `flang` - This is from the tests printout:

```
meson.build:31:0: ERROR: Unable to detect linker for compiler `flang -Wl,--version`
stdout: LINK : warning LNK4044: unrecognized option '/-version'; ignored
LINK : warning LNK4001: no object files specified; libraries used
LINK : warning LNK4068: /MACHINE not specified; defaulting to X64
flangmain.lib(flangmain.c.obj) : error LNK2019: unresolved external symbol MAIN_ referenced in function main
a.exe : fatal error LNK1120: 1 unresolved externals

stderr: flang.exe: error: linker command failed with exit code 1120 (use -v to see invocation)
```

**Comment by marcomangano** [comment]
@nwu63 I figured out why this PR is still failing: the bugfix has not actually been included in the [1.3.1 release](https://github.com/mesonbuild/meson/compare/1.3.1...master). Since we are getting `meson` via `pip` we need to wait for a new release - I don't believe this is urgent enough to require other workarounds?

**Comment by nwu63** [comment]
Thanks for looking this up. Let's wait for a new version then.

**Review by sseraj — APPROVED** [review]

**Review by marcomangano — APPROVED** [review]
I missed the new release, thanks for catching this

**Pull request merged**
