### PR TITLE
Updating minimum dependency requirements

### PR DESCRIPTION
**Pull request by marcomangano**
## Purpose

Issues like #387 show that the current minimum dependency versions are out of date - even considering our own [stencil of supported dependencies](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/installInstructions/install3rdPartyPackages.html#supported-dependency-versions).
I updated the minimum numpy and scipy versions to our `stable` set of dependencies.

However, I think we should also update the `mdolab-baseclasses` version and, more importantly, the minimum python version. The code itself is not changing but this would create issues for the users who are still relying on older python environments.

@ewu63 suggests to adopt the [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) (or the more recent [SPEC  0](https://scientific-python.org/specs/spec-0000/) policy) to avoid this issue, but I think at that point we should extend this to the whole organization packages.
I want to hear @eirikurj take as well as he has been working on a way to map these dependencies over time.

## Expected time until merged

1 day if we are ok with only updating numpy and scipy

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by sseraj — APPROVED** [review]
Just updating numpy and scipy for now is fine with me

**Comment by eirikurj** [comment]
@marcomangano just to formally respond and for future reference. I am in favor of SPEC 0 for our codebase. We have been discussing this in https://github.com/mdolab/docker/issues/241 and should continue there.

**Comment by marcomangano** [comment]
Bumped the minor version since the minimum version update could potentially be a breaking change?

**Comment by marcomangano** [comment]
@sseraj @lamkina  @eirikurj  can you check this out to see if got the right package versions? We should merge ASAP and make a new release.

**Review by sseraj — APPROVED** [review]
This looks good

**Review by eirikurj — APPROVED** [review]
Looks good. ~~Just to clarify, do you want to wait for the docker PR?~~ Nervermind, no need to wait.

**Pull request merged**
