### PR TITLE
Cast funcs to real

### LINKED ISSUE #76: Make stored funcs values real instead of complex
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Bugfix (non-breaking change which fixes an issue)

## Description
Due to complex casting for complex step derivatives, the `funcs` values are complex. They should be cast back to real to be saved in the history file.

### Current behavior
The `funcs` values are complex with zero imaginary components

### Expected behavior
They should be real valued

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

Resolves #76

I added a loop over funcs in _masterFunc2 to cast all values to real. I also removed some now redundant casting that would have occured after the call to _masterFunc2. This includes reverting the commits in #102.

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Testing
Run `test_hs015.py`, which includes new tests in `check_hist_file`.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
Do you know where the complex numbers are being introduced? Instead of patching it like this, I would prefer to fix it at the source. I suspect it's due to some incorrect type passed to the `Gradient` class or something like that.

**Comment by sseraj** [comment]
Actually for `test_hs015.py`, which I was using as a test case, the complex numbers are introduced in `objfunc` from `conval = np.zeros(2, "D")`. I replaced this with `conval = np.zeros(2, "d")`, and there were no complex numbers even without the patch.

**Comment by nwu63** [comment]
The problem is a bit more complex than that.

1. Please keep the test you wrote, but remove the fix where you cast everything to real. If changing the type from `D` to `d` fixes it for `hs015`, let's keep that.

2. The issue is more specifically for when we use complex step to compute derivatives. See for example `test_tp109`. The `funcs` you get from the SNOPT run will be complex. That needs to be addressed and I think it's probably in the complex step part of the code.

**Comment by sseraj** [comment]
Thanks! I was just looking for an example that uses complex step. This patch does not work for `test_tp109` anyway, so I'm going to close this PR and address the root of the problem as you suggested.

**Pull request closed without merging**
