### PR TITLE
Fix test for earlier SNOPT versions

### LINKED ISSUE #369: SNOPT tests failing on stable images
## Description
With changes from PR https://github.com/mdolab/pyoptsparse/pull/364, SNOPT tests are failing on stable images during nightly tests with `fStar` reported as 0 (see for example [here](https://github.com/mdolab/docker/actions/runs/7096395939/job/19314852484#step:13:13471)).

### Steps to reproduce issue
Any stable image with changes from https://github.com/mdolab/pyoptsparse/pull/364 will generate similar errors as below

```
Traceback (most recent call last):
  File "/home/mdolabuser/repos/pyoptsparse/tests/test_tp109.py", line 205, in test_autorefine
    self.assert_solution_allclose(sol2, 1e-2)
  File "/home/mdolabuser/repos/pyoptsparse/tests/testing_utils.py", line 123, in assert_solution_allclose
    assert_allclose(sol.fStar, self.fStar[self.sol_index], atol=tol, rtol=tol)
  File "/home/mdolabuser/.pyenv/versions/3.9.16/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/mdolabuser/.pyenv/versions/3.9.16/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.01

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 5362.06927538
Max relative difference: 1.
 x: array(0.)
 y: array(5362.069275)
```

### Current behavior
SNOPT tests on stable images are failing

### Expected behavior
All tests should pass

### Code versions
Any stable image with changes from https://github.com/mdolab/pyoptsparse/pull/364

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose

Closes #369.

## Expected time until merged

ASAP.

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
Can someone with access test whether the offending test passes with SNOPT 7.7.5? If so then I'd propose bumping the SNOPT version rather than trying to patch very outdated SNOPT versions within pySNOPT. CC @eirikurj

**Comment by eirikurj** [comment]
For completeness, I tried 7.7.5 and tests still fail. Is that however not expected since `sol.objectives` is now being [overwritten](https://github.com/mdolab/pyoptsparse/blob/75e647938b4eee3f3620ea3b8756d52aa2c206f9/pyoptsparse/pyOpt_solution.py#L53) with `fStar`, which is the buggy zero `obj` value returned from SNOPT?

**Comment by nwu63** [comment]
Hm I had thought that maybe 7.7.5 fixed the bug, but perhaps not. A few options:
1. add a version check in pySNOPT to not overwrite `sol.objectives` values for versions 7.7 below 7.7.7.
2. hack or skip the tests for buggy SNOPT versions

I am in favour of the first option since with the changes in #364, buggy SNOPT optimizations essentially lose the optimal objective value, while previously you can at least get the last queried value via `sol.objectives` which is often times close. I'm going to push a patch following 1) but happy to hear other opinions.

**Comment by nwu63** [comment]
Right, I forgot to un-scale the obj values. Thanks, LGTM

**Review by lamkina — APPROVED** [review]
LGTM

**Comment by nwu63** [comment]
@eirikurj or @sseraj let's merge this so we don't fail the nightly build?

**Comment by eirikurj** [comment]
Yeah, tests have been failing for a while. @sseraj do you have time to review this or anyone from @mdolab/pyoptsparse_maintainers? If not, I will merge at end of week.

**Review by sseraj — APPROVED** [review]

**Pull request merged**
