### PR TITLE
Installation docs update

### PR DESCRIPTION
**Pull request by kanekosh**
## Purpose

This PR adds installation instructions using OpenMDAO's `build_pyoptsparse` script on the installation documentation page.
This script has already been mentioned on the IPOPT page, but I think it's worth putting this on the installation page for more attention. (This script is probably the easiest way to install IPOPT and SNOPT, especially on macOS, but I recently realized that some people are not aware of it.)

## Expected time until merged

a week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by ArshSaja** [comment]
Nice!, just a quick question, is IPOPT an open-source? if So, we can point out that.

**Comment by kanekosh** [comment]
> Nice!, just a quick question, is IPOPT an open-source? if So, we can point out that.

Yes, IPOPT is open source and that is already mentioned in https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/optimizers/IPOPT.html

**Comment by ArshSaja** [comment]
> > Nice!, just a quick question, is IPOPT an open-source? if So, we can point out that.
> 
> Yes, IPOPT is open source and that is already mentioned in https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/optimizers/IPOPT.html . So I think we don't have to say that on the installation page?

Yes, forgot it is mentioned there.  For consistency, we can point out the IPOPT installation page similar to how you are pointing out the SNOPT installation page.

**Comment by kanekosh** [comment]
@ArshSaja added the link to the IPOPT page.

@marcomangano I think the line you added about the SNOPT precompiled library better fits under the `conda` section, so I moved it. Does this look good to you?

**Comment by ArshSaja** [comment]
> @ArshSaja added the link to the IPOPT page.
> 
> @marcomangano I think the line you added about the SNOPT precompiled library better fits under the `conda` section, so I moved it. Does this look good to you?

Thanks, looks good!

**Comment by marcomangano** [comment]
> @marcomangano I think the line you added about the SNOPT precompiled library better fits under the `conda` section, so I moved it. Does this look good to you?

Yeah fair, the details are in the SNOPT page anyway!

**Comment by marcomangano** [comment]
Tests are passing but somehow the info is not passed back from Azure. For now, can @eirikurj or @anilyil override the test requirements and merge this? Thx

**Review by eirikurj — APPROVED** [review]
Builds should be reported properly now. Unrelated, but we really should do something about codecov...

**Pull request merged**
