### PR TITLE
Test coverage

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
This PR modifies some coverage-related files, and tests that everything is working as expected.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

### CODE REVIEW

**Comment by nwu63** [comment]
Everything works! :tada:

**Comment by marcomangano** [comment]
@nwu63 I am not authorized to check the Codecov report

**Comment by nwu63** [comment]
Just tested and the checksum I added also works.

**Review by sseraj — APPROVED** [review]
> I am not authorized to check the Codecov report

@marcomangano I also got this message, but I think it only happens in the few minutes after a commit. It should work now.

**Review by marcomangano — APPROVED** [review]

**Pull request merged**
