### PR TITLE
NSGA2 patch

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose

Merge the patch from conda-forge/pyoptsparse-feedstock#36 upstream.

## Expected time until merged

1 week

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
Just rebased the code @marcomangano @ArshSaja

**Comment by eirikurj** [comment]
Strange that this is showing up now. @nwu63 for my information, what triggered this, and what was the system/compiler?

**Comment by nwu63** [comment]
> Strange that this is showing up now. @nwu63 for my information, what triggered this, and what was the system/compiler? Also, why is codecov reporting a large drop?

@whophil did this for the mac build, not sure what the root cause was. Maybe something changed in the toolchain within conda?
Coverage change is due to the PR being submitted on a fork, so some optimizers are skipped. Those should be irrelevant since there are only NSGA2-related changes here, which are covered in the public images.

**Comment by whophil** [comment]
@eirikurj @nwu63 the problem this patch was meant to fix first started appearing on builds after conda-forge moved from clang(x) 15 to 16 for Mac builds. I don't suppose this project is built with clang compilers on CI, but I imagine the error could be reproduced by attempting a build of the main branch with clang 16.

**Comment by whophil** [comment]
Here is a relevant excerpt from the Clang 16 release notes (https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html)

> The -Wimplicit-function-declaration and -Wimplicit-int warnings now default to an error in C99, C11, and C17. As of C2x, support for implicit function declarations and implicit int has been removed, and the warning options will have no effect. Specifying -Wimplicit-int in C89 mode will now issue warnings instead of being a noop.

**Comment by eirikurj** [comment]
Thanks for the info. I looked a bit into this with GCC and there is a warning that is thrown, 
```
../pyoptsparse/pyNSGA2/source/eval.c:25:5: warning: implicit declaration of function ‘nsga2func’ [-Wimplicit-function-declaration]
```
The patch removes this warning.

**Review by eirikurj — APPROVED** [review]

**Comment by nwu63** [comment]
Bump @marcomangano @ArshSaja

**Review by marcomangano — APPROVED** [review]
Thanks for taking care of this, LGTM. Making a new release asap so that the patch can be removed from conda-forge

**Pull request merged**
