### PR TITLE
Removed extra f2py wrapper files

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
As far as I can tell, these files are auto-generated by `f2py` during compilation, and were committed into the repo by accident. This PR removes these unnecessary files.

I have also removed the dash test in python since it was poorly designed, and also wasn't really testing anything anyways.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
All existing tests should pass.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by marcomangano — APPROVED** [review]

**Comment by nwu63** [comment]
The dash test was poorly designed -- the subprocess doesn't get killed cleanly so repeated execution will cause subsequent tests to fail. I've removed the test for the time being.

**Comment by sseraj** [comment]
Where did the issue with the dash test show up? All the tests seem to have passed before the dash test was removed.

**Comment by nwu63** [comment]
> Where did the issue with the dash test show up? All the tests seem to have passed before the dash test was removed.

It's fine on Azure, but try it locally -- the server doesn't get killed properly. So if you run `testflo` again the dash test will fail the second time.

**Comment by sseraj** [comment]
> It's fine on Azure, but try it locally -- the server doesn't get killed properly. So if you run `testflo` again the dash test will fail the second time.

It's actually working fine for me. Maybe @marcomangano can check as well.

**Comment by marcomangano** [comment]
> It's actually working fine for me. Maybe @marcomangano can check as well.

I think this is exactly the kind of problem I mentioned before in our chat, the second time I run the tests `test_optview_dash` fails with `AssertionError: TimeoutExpired not raised` and testflo stalls after all the other tests are run.

**Review by sseraj — APPROVED** [review]
Interesting. It's probably best to remove the dash test then.

**Review by marcomangano — APPROVED** [review]

**Pull request merged**
