### PR TITLE
Fix for multiplier post-processing code

### PR DESCRIPTION
**Pull request by gjkennedy**
## Purpose
I fixed the code that post-processes the multipliers after the optimization.

## Type of change
- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Testing
I added a test to test_hs071.py to test the multiplier values.

## Checklist
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
@gjkennedy @JustinSGray  I tried to do the same thing for SLSQP since it also provides Lagrange multipliers, but that runs into 2 problems. 1) there is dimension mismatch for TP109, and 2) the value does not match what you get with SNOPT in HS71. I did verify that the "correct" value in the test is somewhere in the `w` vector in pySLSQP, but I don't know how to go about extracting it. So it seems that the multiplier values in SLSQP are not correct when there is no dimension conflict.

So, if @JustinSGray doesn't need the multipliers in SLSQP then I will just remove `sol.pi` altogether, and only save the multipliers in SNOPT under `lambdaStar` which are scaled. Does that sound good?

**Comment by JustinSGray** [comment]
If possible, I think we should try to get the multipliers from SLSQP. Not everyone has SNOPT, and the multipliers are really valuable for scaling. 

I wouldn't let them hold up progress, but we do have the source for SLSQP right there in the repo. They really should be accessible. no?

**Comment by gjkennedy** [comment]
I've figured out how to extract multipliers from SLSQP. The code that was there was wrong - the variables pi were not the correct values. The multipliers are the first m entries of the w array.

However, the deProecessConstraints function in pyOpt_optimization.py is definitely wrong, and has been this whole time.

**Comment by nwu63** [comment]
Yeah there is some inconsistency with how constraints are counted, linear vs. nonlinear. I don't really know what the variables `optProb.offset` and `optProb.fact` are, so I wasn't really sure how to go about dealing with this. @gkenway and @camader may be able to help?

**Comment by gjkennedy** [comment]
So while, in general, it would be great to have all the optimizers return multipliers, that's clearly beyond the scope of this pull request. It just addresses SNOPT and ParOpt. Others should address the general case right?

**Comment by jrram** [comment]
I agree with Graeme. Better to release a new feature that is only available for a couple of optimizers instead of requiring that all of them be supported (which might never happen).

**Comment by nwu63** [comment]
Okay, merging.

**Pull request merged**
