### PR TITLE
Update Travis

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
This PR is used to update Travis (yet again) as we iterate the new Travis setup (via shared imports).
- Removed black/flake8 checks via GitHub Actions
- Added Travis check jobs for those
- Updated flake8 file since a shared MDO Lab one is provided

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
This PR is for testing! Doesn't change coverage just updates Travis

### CODE REVIEW

**Comment by nwu63** [comment]
Alright I think this is finally ready, thankfully we're squashing all the commits.

**Review by sseraj — APPROVED** [review]
Looks good!

**Review by marcomangano — APPROVED** [review]

**Comment by sseraj** [comment]
The tests actually failed for some reason.

**Comment by nwu63** [comment]
Should be good now, I think there was some service disruption with Docker Hub or something, but `docker pull` was just hanging there.

**Pull request merged**
