### PR TITLE
Added note in documentation on macOS/Windows builds

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
Added note in documentation on potential (and unsupported) macOS/Windows builds.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

### CODE REVIEW

**Review by marcomangano — APPROVED** [review]

**Comment by sseraj** [comment]
Do we want to wait on merging this until we hear from @jackm97 on whether the tests pass on Windows?

**Comment by jackm97** [comment]
> 
> 
> Do we want to wait on merging this until we hear from @jackm97 on whether the tests pass on Windows?

I'm currently running the tests. It looks like most, but not all of the tests are passing. I'm however dealing with a lot of Windows specific errors like `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'optProb_SLSQP.out'` that don't necessarily mean the test is actually failing.

That said, it seems the nsga2 multi objective tests are actually broken and something in the rosenbrock tests is broken. I don't have snopt so I don't have a way of testing. I will update with better info when I can.

**Comment by nwu63** [comment]
> I'm currently running the tests. It looks like most, but not all of the tests are passing. I'm however dealing with a lot of Windows specific errors like `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'optProb_SLSQP.out'` that don't necessarily mean the test is actually failing.

You might find that running `testflo` with `-n 1`, which forces sequential test execution, will help. This is also insightful though, in that we may have multiple tests writing to the same file which is not good. If the `-n 1` flag solves the issue, would you mind opening a separate issue for that?

> That said, it seems the nsga2 multi objective tests are actually broken and something in the rosenbrock tests is broken. I don't have snopt so I don't have a way of testing. I will update with better info when I can.

Can you post the full list of failed tests and the log? I suspect your NSGA2 installation is broken since that will require SWIG, so having that compiled on Windows seem like a real challenge.

**Comment by jackm97** [comment]
@nwu63 Running `testflo -n 1 .` completely solved the problem. I can open a new issue.

All tests that I can run, including NSGA2, pass with the SNOPT, ParOpt, and NLPQLP are skipped because I don't have them. To get NSGA2 working you can get SWIG and the optimizer through conda ([NSGA2](https://anaconda.org/conda-forge/r-nsga2r) and [SWIG](https://anaconda.org/anaconda/swig)).

# Testflo log:

```
.\tests\test_hs015.py:TestHS15.test_ipopt ... OK (00:00:0.81, 0 MB)
.\tests\test_hs015.py:TestHS15.test_optimization_0_SLSQP ... OK (00:00:0.01, 0 MB)
.\tests\test_hs015.py:TestHS15.test_optimization_1_PSQP ... OK (00:00:0.00, 0 MB)
.\tests\test_hs015.py:TestHS15.test_optimization_2_CONMIN ... OK (00:00:0.01, 0 MB)
.\tests\test_hs015.py:TestHS15.test_optimization_3_NLPQLP ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'NLPQLP')
.\tests\test_hs015.py:TestHS15.test_optimization_4_ParOpt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'ParOpt')
.\tests\test_hs015.py:TestHS15.test_snopt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_hs071.py:TestHS71.test_ipopt_informs ... OK (00:00:0.05, 0 MB)
.\tests\test_hs071.py:TestHS71.test_nlpqlp_informs ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'NLPQLP')
.\tests\test_hs071.py:TestHS71.test_optimization_0_SNOPT ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_hs071.py:TestHS71.test_optimization_1_IPOPT ... OK (00:00:0.28, 0 MB)
.\tests\test_hs071.py:TestHS71.test_optimization_2_SLSQP ... OK (00:00:0.01, 0 MB)
.\tests\test_hs071.py:TestHS71.test_optimization_3_PSQP ... OK (00:00:0.01, 0 MB)
.\tests\test_hs071.py:TestHS71.test_optimization_4_CONMIN ... OK (00:00:0.05, 0 MB)
.\tests\test_hs071.py:TestHS71.test_optimization_5_NLPQLP ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'NLPQLP')
.\tests\test_hs071.py:TestHS71.test_optimization_6_ParOpt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'ParOpt')
.\tests\test_hs071.py:TestHS71.test_psqp_informs ... OK (00:00:0.00, 0 MB)
.\tests\test_hs071.py:TestHS71.test_slsqp_informs ... OK (00:00:0.00, 0 MB)
.\tests\test_hs071.py:TestHS71.test_slsqp_scaling_offset_optProb ... OK (00:00:0.11, 0 MB)
.\tests\test_hs071.py:TestHS71.test_slsqp_setDV ... OK (00:00:0.08, 0 MB)
.\tests\test_hs071.py:TestHS71.test_snopt_informs ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_hs071.py:TestHS71.test_snopt_setDVFromHist ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_large_sparse.py:TestLarge.test_dense_workspace_too_small ... SKIP (00:00:0.02, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_large_sparse.py:TestLarge.test_opt_0_SNOPT ... SKIP (00:00:0.32, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_large_sparse.py:TestLarge.test_opt_1_IPOPT ... OK (00:00:23.59, 0 MB)
C:\Users\Jack\Documents\Build From Source\pyoptsparse\build\lib.win-amd64-3.9\pyoptsparse\pyOpt_utils.py:221: UserWarning: Using scipy.sparse matrices with pyOptSparse is VERY STRONGLY discouraged. Please use the simplified pyOptSparse format which allows for fixed sparsity structure and explicit zeros in the matrix. There is no way to guarantee a fixed sparsity structure with scipy matrices which is what the underlying optimizers require. Using scipy.sparse matrices may cause unexpected errors.
  warnings.warn(

.\tests\test_large_sparse.py:TestLarge.test_opt_2_SNOPT ... SKIP (00:00:0.02, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_nsga2_multi_objective.py:TestNSGA2.test_opt ... OK (00:00:4.07, 0 MB)
.\tests\test_optProb.py:TestOptProb.test_finalize ... OK (00:00:0.02, 0 MB)
.\tests\test_optProb.py:TestOptProb.test_mappings ... OK (00:00:0.05, 0 MB)
.\tests\test_optProb.py:TestOptProb.test_setDV_VarGroup ... OK (00:00:0.04, 0 MB)
.\tests\test_optProb.py:TestOptProb.test_setDV_getDV ... OK (00:00:0.04, 0 MB)
.\tests\test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_do_not_use_mpi ... OK (00:00:0.00, 0 MB)
.\tests\test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_no_mpi_requirement_given ... OK (00:00:0.00, 0 MB)
.\tests\test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_require_mpi ... OK (00:00:0.00, 0 MB)
.\tests\test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_do_not_use_mpi_check_paropt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available:', 'paropt')
.\tests\test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_no_mpi_requirement_given_check_paropt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available:', 'paropt')
.\tests\test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_require_mpi_check_paropt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available:', 'paropt')
.\tests\test_rosenbrock.py:TestRosenbrock.test_optimization_0_IPOPT ... OK (00:00:16.99, 0 MB)
.\tests\test_rosenbrock.py:TestRosenbrock.test_optimization_1_SLSQP ... OK (00:00:1.57, 0 MB)
.\tests\test_rosenbrock.py:TestRosenbrock.test_optimization_2_PSQP ... OK (00:00:0.91, 0 MB)
.\tests\test_rosenbrock.py:TestRosenbrock.test_optimization_3_CONMIN ... OK (00:00:4.95, 0 MB)
.\tests\test_rosenbrock.py:TestRosenbrock.test_optimization_4_NLPQLP ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'NLPQLP')
.\tests\test_rosenbrock.py:TestRosenbrock.test_optimization_5_ParOpt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'ParOpt')
.\tests\test_rosenbrock.py:TestRosenbrock.test_snopt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_snopt_bugfix.py:TestSNOPTBug.test_opt ... SKIP (00:00:0.00, 0 MB)
Optimizer not available: SNOPT
.\tests\test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug1 ... SKIP (00:00:0.00, 0 MB)
Optimizer not available: SNOPT
.\tests\test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug_print_2con ... SKIP (00:00:0.00, 0 MB)
Optimizer not available: SNOPT
.\tests\test_snopt_user_termination.py:TestUserTerminationStatus.test_obj ... SKIP (00:00:0.00, 0 MB)
Optimizer not available: SNOPT
.\tests\test_snopt_user_termination.py:TestUserTerminationStatus.test_sens ... SKIP (00:00:0.00, 0 MB)
Optimizer not available: SNOPT
.\tests\test_tp109.py:TestTP109.test_autorefine ... SKIP (00:00:12.82, 0 MB)
('Optimizer not available: ', 'SNOPT')
.\tests\test_tp109.py:TestTP109.test_slsqp ... OK (00:00:0.04, 0 MB)
.\tests\test_tp109.py:TestTP109.test_snopt ... SKIP (00:00:0.00, 0 MB)
('Optimizer not available: ', 'SNOPT')


OK

Passed:  27
Failed:  0
Skipped: 25


Ran 52 tests using 1 processes
Wall clock time:   00:01:7.27


```

**Review by sseraj — APPROVED** [review]

**Pull request merged**
