### PR TITLE
Optview dash

### PR DESCRIPTION
**Pull request by alexishonzik**
## Purpose
This pull request is in order to add the OptView tool created with the Dash framework to pyoptsparse. I've made the following changes:
- added a OptView_dash.py file and corresponding assets
- deleted old Dash file (and corresponding assets)
- minor changes to setup.py
	- register `optview_dash` as a new CLI tool
	- added optional dependency set "optview"
- moved the old OptView icon to the assets folder
- updated documentation
- added a test for OptView-Dash (cannot test OptView due to GUI)
- updated Travis
- changed line ending for some files from CRLF to LF

Apologies for the large number of file changes due to line ending, I could revert this and submit as a separate PR if it would be better for reviewing this PR.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other

## Testing
Please do the following to test
1. Install the package (both in-place and full installation are supported)
2. invoke `optview_dash <file>` on an existing optimization history file. You can use one of the files generated by the tests if you like
3. Verify that OptView-Dash works as expected.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
I've updated the PR description with some more information. @sseraj @marcomangano please verify that this works following the Testing section described above.

**Review by marcomangano — COMMENTED** [review]
Will test later locally, but looks good so far! @nwu63 can you explain what you did [in this commit](https://github.com/mdolab/pyoptsparse/pull/200/commits/19f0346268210ac7186aaba79e53ab97167d8ca3)?

**Comment by nwu63** [comment]
> Will test later locally, but looks good so far! @nwu63 can you explain what you did [in this commit](https://github.com/mdolab/pyoptsparse/pull/200/commits/19f0346268210ac7186aaba79e53ab97167d8ca3)?

Yeah, this is me changing line endings for some files from CRLF (Windows) to LF (Unix). Because this touches every line it shows up as a huge diff. See [here](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings) for some info.

This is what I was saying earlier, I can remove this and make that a separate PR if you want.

**Comment by marcomangano** [comment]
> This is what I was saying earlier, I can remove this and make that a separate PR if you want.

Yeah, now that I am checking all the files affected, most of them unrelated to OptView, it might be better to have a dedicated PR for that.. Is that a big issue to revert that commit specifically?

**Comment by nwu63** [comment]
> Yeah, now that I am checking all the files affected, most of them unrelated to OptView, it might be better to have a dedicated PR for that.. Is that a big issue to revert that commit specifically?

I can revert that specific commit easily here. Let me do that and push up.

**Comment by marcomangano** [comment]
Looks good! Early tomorrow I will test this locally and approve

**Review by sseraj — COMMENTED** [review]
The installation and functionality both work as expected. Just one thing: I think we can remove the `.flake8` file now that OptView is linted.

**Comment by sseraj** [comment]
Okay, they were not linted. I don't know why I thought they were.

**Review by sseraj — APPROVED** [review]

**Review by marcomangano — APPROVED** [review]
It works! Good job everybody

**Pull request merged**
